// --- IMPORTS ---
import { useEffect, useState, useRef } from 'react';
// The WASM bridge automatically generated by wasm-pack
import init, { AnimLabEngine } from 'animlab-core';
// Our pure TypeScript input interceptor
import { GlobalInputManager } from './engine_bridge/InputManager';

export default function App() {
  // --- UI STATE ---
  // useState is ONLY for variables that should physically change the HTML/CSS on the screen.
  // Changing this will cause React to re-render the Top UI Bar.
  const [status, setStatus] = useState<string>('Initializing bridge...');
  
  // --- ENGINE MEMORY POINTERS ---
  // useRef is for variables that exist completely outside of React's visual rendering cycle.
  // We can change these 10,000 times a second and React will never lag or redraw the screen.
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<AnimLabEngine | null>(null);
  const inputManagerRef = useRef<GlobalInputManager | null>(null);
  
  // Holds the ID of the browser's render loop so we can stop it later.
  const reqFrameRef = useRef<number>(0);
  
  // React 18 mounts components twice in development mode. This lock prevents 
  // the heavy Rust engine from booting twice and crashing the memory bridge.
  const isBootingRef = useRef<boolean>(false);

  // --- COMPONENT LIFECYCLE ---
  // useEffect runs exactly once when this component is first drawn to the screen.
  useEffect(() => {
    // If we are already booting, immediately exit.
    if (isBootingRef.current) return;
    isBootingRef.current = true;

    async function bootEngine() {
      try {
        // 1. Fetch and load the raw .wasm binary into browser memory.
        await init();
        
        // 2. Instantiate the Rust engine.
        const engine = new AnimLabEngine();
        engineRef.current = engine;
        
        // Update the visual UI state.
        setStatus(engine.get_system_status());

        // 3. If the HTML canvas has successfully loaded on the screen...
        if (canvasRef.current) {
          // Grab the physical pixel dimensions of the user's monitor.
          const width = canvasRef.current.clientWidth;
          const height = canvasRef.current.clientHeight;
          
          // Lock the canvas memory to those exact dimensions to prevent blurry rendering.
          canvasRef.current.width = width;
          canvasRef.current.height = height;

          // 4. Hand the canvas memory pointer over to Rust and WebGPU.
          await engine.attach_canvas(canvasRef.current, width, height);

          // 5. Instantiate our Single Source of Truth for input.
          // By passing both the canvas and the engine, this manager can now intercept 
          // mouse events and pipe them directly to Rust without waking React up.
          inputManagerRef.current = new GlobalInputManager(canvasRef.current, engine);

          // 6. Define the Render Loop.
          const renderLoop = () => {
            if (engineRef.current) {
              engineRef.current.render(); // Tell Rust to draw
            }
            // Ask the browser to call this loop again on the next monitor V-Sync.
            reqFrameRef.current = requestAnimationFrame(renderLoop);
          };
          
          // Ignite the loop.
          renderLoop();
        }
      } catch (err) {
        console.error('Engine boot failed:', err);
        setStatus('FATAL: Failed to boot WebAssembly core.');
      }
    }

    bootEngine();

    // --- ZERO-DEBT CLEANUP ---
    // This return function acts as the destructor. It runs when the app is closed or refreshed.
    return () => {
      // 1. Stop requesting new frames.
      cancelAnimationFrame(reqFrameRef.current);
      
      // 2. Sever the DOM event listeners to prevent input memory leaks.
      if (inputManagerRef.current) {
        inputManagerRef.current.dispose();
        inputManagerRef.current = null;
      }

      // 3. Manually free the Rust WebAssembly memory. 
      // If we skip this, the WASM blob stays in the browser's RAM forever.
      if (engineRef.current) {
        engineRef.current.free();
        engineRef.current = null;
      }
    };
  }, []); // The empty array [] guarantees this effect only runs on mount.

  // --- THE UI VIEWPORT ---
  return (
    <div style={{ width: '100vw', height: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: '#000' }}>
      
      {/* Top UI Bar (React controlled) */}
      <div style={{ height: '40px', backgroundColor: '#111', borderBottom: '1px solid #333', display: 'flex', alignItems: 'center', padding: '0 20px', color: '#888', fontSize: '12px', fontFamily: 'monospace', zIndex: 10 }}>
        AnimLab Pre-Alpha | {status}
      </div>
      
      {/* The WebGPU Canvas Container */}
      {/* touchAction: 'none' is a critical CSS rule that prevents the browser from trying to scroll or zoom the page when drawing with a pen or finger. */}
      <div style={{ flex: 1, position: 'relative', touchAction: 'none' }}>
        <canvas 
          ref={canvasRef} 
          style={{ width: '100%', height: '100%', display: 'block', cursor: 'crosshair' }} 
        />
      </div>
      
    </div>
  );
}